### ISSUE TITLE
Rerunning pipelines may not work with --project flag.

### ISSUE THREAD

**Issue by RAsadi** [KnapsackPro/knapsack-pro-cypress#53]
Running into a small issue with using this package, specifically in regards to using the `--project` flag on cypress and using the `KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true` env variable. Bit of a text dump here, sorry about that 😅 . For context, I'm using Bitbucket Pipelines, and the config file looks something like

```
      - step:
          name: Cypress 1/N
          script:
          - export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
          - export KNAPSACK_PRO_TEST_FILE_PATTERN=subdir1/subdir2/cypress/integration/**/*.js
          - <All other knapsack pro env variables set appropriately>
          - yarn install --frozen-lockfile
          - yarn cypress install
          - yarn run knapsack-pro-cypress --project subdir1/subdir2
```
On first run, this works great. However, when rerunning a failed pipeline, instead of passing in the file paths as `subdir1/subdir2/cypress/integration/<sometestfile>`, cypress seems to be instead called with `cypress/integration/<sometestfile>`, which results in an error that looks like:

```
Can't run because no spec files were found.
We searched for any files matching this glob pattern:
../../cypress/integration/<sometestfile>.
```

I did a bit of digging about why this might be, and in the knapsack-pro-cypress.ts, line 61 you have:
```
  const recordedTestFiles: TestFile[] = tests.map((test: any) => ({
    path: test.spec.relative,
    time_execution:
      // test.stats.wallClockDuration - Cypress 3.x and 4.x
      // test.stats.duration - Cypress 5.x
      (test.stats.wallClockDuration || test.stats.duration) / 1000,
  }));
```
Based on what cypress says in their code here: https://github.com/cypress-io/cypress/blob/4d76049d2c419d77968beafcdda45585744fc542/cli/types/cypress-npm-api.d.ts, `test.spec.relative` returns paths relative to the project root. So, because I set the project root to be `subdir1/subdir2`, the path returned by `test.spec.relative` will be `cypress/integration/<sometestfile>`. Not going to pretend I know how the internals of the API (or client for that matter) work, but I'm assuming that this is later used to deal with rerunning a pipeline when the `KNAPSACK_PRO_FIXED_QUEUE_SPLIT` env var is set to true.

So, the file path that cypress is called with on the first and 2nd run will be different, and while the first run works great, any reruns of the pipeline will break.

I think the solution to this could either be as simple as changing `test.spec.relative` to `test.spec.absolute`, or by just using the file paths that are originally provided instead of the file paths that `cypress.run` returns. FWIW, I think the first solution I proposed might not work for all CI runners, for example if the absolute path would change on rerun (haven't seen this for bitbucket but it could be the case for other CI runners), but I think the second solution would probably work?

More than happy to put up a PR for this with either proposed solution, just let me know!

Thanks!!

**Comment by ArturT** [comment]
Can't you run knapsack command from the proper directory instead of using project option? Could you try that?

**Comment by ArturT** [comment]
If you need to run only test files from a single directory please use this https://knapsackpro.com/faq/question/how-to-run-tests-only-from-specific-directory-in-cypress instead of project option.

**Comment by ArturT** [comment]
> I think the solution to this could either be as simple as changing test.spec.relative to test.spec.absolute, or by just using the file paths that are originally provided instead of the file paths that cypress.run returns. FWIW, I think the first solution I proposed might not work for all CI runners, for example if the absolute path would change on rerun (haven't seen this for bitbucket but it could be the case for other CI runners), but I think the second solution would probably work?

We should not use `test.spec.absolute` because when you run tests on the different environments the absolute path could be different. Sometimes people run tests in development, or migrate between CI providers, or change something in the config on CI, etc.

> by just using the file paths that are originally provided instead of the file paths that cypress.run returns.

I've check this idea but it might be hard to implement or error-prone to match test file paths to recorded tests returned by `cypress.run`. We need information about the time execution of each test file. 
`cypress.run` already returns path + time execution information. 

https://github.com/KnapsackPro/knapsack-pro-cypress/blob/2f6537eaf85a58aa0ba9d3fb8f8470466c24c78f/src/knapsack-pro-cypress.ts#L48,L67


I recommend to do this `cd subdir1/subdir2 && yarn run knapsack-pro-cypres`

```yml
      - step:
          name: Cypress 1/N
          script:
          - export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
          - export KNAPSACK_PRO_TEST_FILE_PATTERN=subdir1/subdir2/cypress/integration/**/*.js
          - <All other knapsack pro env variables set appropriately>
          - yarn install --frozen-lockfile
          - yarn cypress install
          - cd subdir1/subdir2 && yarn run knapsack-pro-cypres
```

Can you check if that works for you?

Do you have any other test files in your project?
Please use a separate API token for each unique set of test files. https://knapsackpro.com/faq/question/how-many-api-keys-i-need

**Comment by RAsadi** [comment]
Thanks for the response!

> I recommend to do this cd subdir1/subdir2 && yarn run knapsack-pro-cypres

Tried this out, seems like `yarn run knapsack-pro-cypress` still runs from the root directory (I'm guessing because theres only one `package.json` defined at the root directory in my project).
However, for a workaround, adding

```
{
  "scripts": {
    "run-knapsack": "cd subdir1/subidr2 && knapsack-pro-cypress"
  },
}
```
to my package.json and changing the `yml` to call `yarn run-knapsack` instead of `yarn run knapsack-pro-cypress --project subdir1/subdir2` seems to work. (Technically I'm running into some out of memory issues with bitbucket, but I doubt that would be related to this package)

> We should not use test.spec.absolute because when you run tests on the different environments the absolute path could be different. Sometimes people run tests in development, or migrate between CI providers, or change something in the config on CI, etc.

Completely fair 👍 

>  I've check this idea but it might be hard to implement or error-prone to match test file paths to recorded tests returned by cypress.run. We need information about the time execution of each test file.
cypress.run already returns path + time execution information.

Yeah, I agree that it might be error-prone. I would have thought that something like 

```
  const { runs: tests, totalFailed } = await cypress.run({
    ...updatedCypressCLIOptions,
    spec: testFilePaths,
  });

  // when Cypress crashed
  if (typeof tests === 'undefined') {
    return {
      recordedTestFiles: [],
      isTestSuiteGreen: false,
    };
  }

  const recordedTestFiles: TestFile[] = tests.map((test: any, idx: number) => ({
-    path: test.spec.relative,
+   path: testFilePaths[idx], 
    time_execution:
      // test.stats.wallClockDuration - Cypress 3.x and 4.x
      // test.stats.duration - Cypress 5.x
      (test.stats.wallClockDuration || test.stats.duration) / 1000,
  }));
```

would work, but it's pretty dependant on the behaviour of `cypress.run` (i.e. it would only work if `cypress.run` returns the completed tests in the same order that they are provided).

I guess another idea off hand would be specifically checking for the `--project` flag, and if its present prepending it to the file paths that are returned from `cypress.run`, but that seems even more error prone than the previous idea.

> Do you have any other test files in your project?
Please use a separate API token for each unique set of test files. https://knapsackpro.com/faq/question/how-many-api-keys-i-need

Yep! Already doing this 👍 . I have some other steps that look like
```
      - step:
          name: Cypress 1/M
          script:
          - export KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true
          - export KNAPSACK_PRO_TEST_FILE_PATTERN=subdir3/subdir4/cypress/integration/**/*.js
          - <All other knapsack pro env variables set appropriately>
          - yarn install --frozen-lockfile
          - yarn cypress install
          - yarn run knapsack-pro-cypress --project subdir3/subdir4
```
(so the same thing except in subdir3/subdir4 instead of subdir1/subdir2, which is the reason we are using the `--project` flag since we have different configurations for cypress in those directories).


Just summing up, adding a yarn command into my `package.json` that cds into the appropriate directory and runs `yarn knapsack-pro-cypress` works as temporary workaround to the issue. Ideally, I think I would still vouch for trying to handle the `--project` flag when rerunning pipelines though, or documenting that the `--project` flag won't work when rerunning pipelines. So, given that I found a workaround but I still think the bug exists with dealing with the `--project` flag, I'll leave the closing of this issue to you. Again, please let me know if you are satisfied with any of the ideas we discussed and I would be happy to put up a PR.

Thanks again!
